//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AMEL2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BerichtsUpdateTrack
    {
        public int Id { get; set; }
        public Nullable<int> Projekt { get; set; }
        public Nullable<int> BN { get; set; }
        public Nullable<int> IT { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
